### ISSUE TITLE
Tail Connection With Custom SSH Port

### ISSUE THREAD

**Issue by wzulfikar** [spatie/laravel-tail#14]
I tried to remote-tail a server which ssh port is 22, and it works. However, when I tried to remote-tail (`artisan tail production`) to another server which ssh port is changed to other than 22, it doesn't work.

to make it works on my side, what I did is adding new optional `port` in config file and add the `-p` option in ssh command.

`TailCommand.php`
![screen shot 2017-02-26 at 2 04 58 am](https://cloud.githubusercontent.com/assets/7823011/23333559/4d3b5c3c-fbc8-11e6-9be0-82fd313b4223.jpg)

`config/tail.php` → using port `8888` as example
![screen shot 2017-02-26 at 2 03 52 am](https://cloud.githubusercontent.com/assets/7823011/23333569/5d38903c-fbc8-11e6-9dce-3a50f5003821.jpg)

is there anything that you already done to configure for custom ssh port? or should i just stick with the code above?

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.
