### ISSUE TITLE
Undefined `port`, related to issue #20

### ISSUE THREAD

**Issue by wzulfikar** [spatie/laravel-tail#21]
In issue #20 @freekmurze fixed undefined `$portCommand`, which I just realised that it also causes error when `port` isn't defined in `config/tail.php`. However, what causes me to open issue #20 is actually the `$port` variable (last line, in attached image).

![screen shot 2017-03-17 at 7 14 37 pm](https://cloud.githubusercontent.com/assets/7823011/24042058/4e35b28a-0b4b-11e7-8254-679a2b7c2100.jpg)

Previously it was defined as `$port = 22` and the value will change accordingly if there's `port` key in `config/tail.php`. 

Since we offer ability to use custom ssh port, displaying port that's being used in console info might be helpful. Thus, `info()` will use the `$port` variable again to display which port is being used.

**Comment by freekmurze** [comment]
Fixed in latest version.

**Comment by wzulfikar** [comment]
thanks!
