### ISSUE TITLE
'tail' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by zhukovsergey** [spatie/laravel-tail#38]
I got this error:
![image](https://user-images.githubusercontent.com/1946769/32547910-80ac75e4-c4b6-11e7-8438-285b86bc7b51.png)

Seems the package use direct command "tail".

**Comment by freekmurze** [comment]
do the other Laravel artisan commands work?

**Comment by freekmurze** [comment]
do you see `tail` in the list of options when you execute `php artisan`?

**Comment by sebastiandedeyne** [comment]
This looks more like an OS error. Does your system support the `tail` command?

Here's where it gets called in the package: https://github.com/spatie/laravel-tail/blob/00ff8b18af54546f906861c6011d5f546ee70dc0/src/TailCommand.php#L30

**Comment by zhukovsergey** [comment]
Command line is works but seems it just doesn't support on windows OS
