### ISSUE TITLE
Feature Request: Additionally output entries from spatie/laravel-activitylog if available

### ISSUE THREAD

**Issue by DeftNerd** [spatie/laravel-tail#49]
`spatie/laravel-tail` can determine if `spatie/laravel-activitylog` and display created ActivityLog events. 

In order to do this, you might need to generate an event on ActivityLog model creation events, which is currently not a part of that package. I'm creating an issue in that repo for that feature now (which is useful, even if this feature request isn't approved)

**Comment by freekmurze** [comment]
Our tail package should not be aware of the activitylogger package. If you need this functionality, create your own package.
