### ISSUE TITLE
Port and SSH key file options

### ISSUE THREAD

**Issue by mnpenner** [spatie/laravel-tail#5]
The command I need to run is something like

```
 ssh vagrant@127.0.0.1 -p 2222 -i D:/path/to/project/.vagrant/machines/default/virtualbox/private_key -T 'cd /var/log/nginx && tail -n50 -f $(ls -t | head -n 1)'
```

Ideally I'd like to be able to log multiple log files too. Do you think you could add a few more options?

**Comment by freekmurze** [comment]
I'd accept a PR for this. Closing this for now.
