### ISSUE TITLE
php-version requirements seems overly restrictive

### ISSUE THREAD

**Issue by troelskn** [spatie/laravel-tail#58]
I have an app running on php 7.3. I can't update to the latest version of this library, since the composer file specifies 7.4 as minimum version. It appears to me that there is no real reason for this requirement and it would work fine with 7.3 and possibly older versions as well. If you agree, would it be possible to lower the requirements and publish a new patch version?

**Comment by freekmurze** [comment]
We used PHP 7.4 specific functionalities in the dependancies of this package.

Feel free to fork our code and mold your fork to your needs.

**Comment by mikeerickson** [comment]
@troelskn Well, there you go :-(

**Comment by mikeerickson** [comment]
@freekmurze Might be a good idea to post the PHP 7.4 requirement on the README so that one does not waste the time trying to install if we aren't running PHP 7.4

**Comment by mikeerickson** [comment]
@freekmurze Which version release did you upgrade requirement for PHP 7.4?
