### ISSUE TITLE
Support Laravel 7 and PHP 7.3

### ISSUE THREAD

**Issue by tquiroga** [spatie/laravel-tail#61]
Laravel 7.x requires PHP>=7.2.5 as stated on the [migration guide](https://laravel.com/docs/7.x/upgrade#upgrade-7.0 )

I'm stuck in the middle of `3.3.0` and `4.0.0` because I use Laravel 7 with PHP 7.3.17.

Any chance you could add support for that without affecting much the current package?

**Comment by freekmurze** [comment]
I don't need this at the moment, so I'm not going to invest time in it.

Please fork the package and adapt it to your needs.
